version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80" # Podrás verlo en localhost:8080
    volumes:
      - .:/var/www/html # Sincroniza tus cambios de código en tiempo real
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nombre_de_tu_bd
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge